### ISSUE TITLE
create napkin diagram in README

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#1]
@visheshdembla @surajp28 @ayishacs  
#First deliverable
Task1: Napkin diagram

**Comment by ayishacs** [comment]
![napkindiagram](https://user-images.githubusercontent.com/77846296/106170656-a8199100-615e-11eb-91df-6b3c883cc985.png)

- [x] created and uploaded napkin daigram.
- [x] peer review by @visheshdembla @surajp28 
- [ ] napkin daigram will be updated in readme

**Comment by visheshdembla** [comment]
@ayishacs can we also get a JPG format downloaded for the final image. This one seems to be a PNG format, where the background is transparent. This doesn't look good if you have a black theme set on GitHub, so could be an issue for some users. I am attaching how it looks on my GitHub, so maybe it would be clear what I am talking about.


<img width="517" alt="npd" src="https://user-images.githubusercontent.com/13031482/106302946-93ed9680-6227-11eb-9137-448da6df4933.PNG">

**Comment by visheshdembla** [comment]
Here are some feedbacks that I gave in our yesterday's sync. 
1. I think since the end-user of the SaaS doesn't care how and where the data is being stored, we should remove the icons for servers.
2. A capability like login is implied and trivial so putting locks in for indicating that we have login seems redundant.
3. The second icon looks a bit like Instagram. Since you mentioned it is supposed to be a camera, should we replace it by a different logo?
4. The feature on group sharing that is indicted by the third computer and a set of users is not clear. Should we think about replacing that with something more relatable?
5. Let's also add some verbs to this so that our napkin diagram becomes easier to understand.
6. Can we somewhere specific the name of the Service (Panorama) so that looking at the diagram a person can identify that it is for our service? I would put it on the top instead of the servers, or replace the cloud with the same. 

Let's have a further discussion on the same if required.

@surajp28 can you post your feedback on the same here.

**Comment by visheshdembla** [comment]
As a potential possibility, we can try defining some personas and create a story in our napkin diagram. Just giving an example of the same on a rough pen paper image.

![napkin_dig](https://user-images.githubusercontent.com/13031482/106326230-22730f80-624a-11eb-93d8-f579b95a7004.jpeg)

**Comment by ayishacs** [comment]
Thank you for your feedback @visheshdembla @surajp28  

Here are my inputs based upon team's feedback during the meeting:

A napkin diagram is a loose drawing to represent a concept, _it may or may not include the architectural components_ such as compute, storage or user management features.  

The audience for napkin diagram include _customers, technical. non-technical and business users_.   

Based on team's feedback, I will go ahead and make these changes in the napkin diagram:

1. Include action verbs and team name in the diagram, as planned in the second draft.  
2. With the intention of keeping it simple and clear, I would look for better alternatives for icons in the tool else the same icons would be retained.  

Please note: 
The icons and images depend entirely on the options provided by visualization tool.
Flexibility in terms of creativity is desired from the team as discussed.

**Comment by ayishacs** [comment]
> @ayishacs can we also get a JPG format downloaded for the final image. This one seems to be a PNG format, where the background is transparent. This doesn't look good if you have a black theme set on GitHub, so could be an issue for some users. I am attaching how it looks on my GitHub, so maybe it would be clear what I am talking about.
> 
> <img alt="npd" width="517" src="https://user-images.githubusercontent.com/13031482/106302946-93ed9680-6227-11eb-9137-448da6df4933.PNG">

The final diagram will be in JPG format.

**Comment by ayishacs** [comment]
![panoramanapkindiagram2](https://user-images.githubusercontent.com/77846296/106660522-1949b180-656e-11eb-991b-c57530433279.jpg)

**Comment by ayishacs** [comment]
![panoramanapkindiagram2](https://user-images.githubusercontent.com/77846296/106662506-76466700-6570-11eb-9b24-185bcaa74bda.jpg)

**Comment by ayishacs** [comment]
@airavata-courses/panorama @visheshdembla @surajp28 

The second draft of the napkin diagram with necessary updates based on feedback is posted. 
Please feel free to give your inputs by commenting in the thread.

**Comment by visheshdembla** [comment]
@ayishacs I guess the organization representation that we had discussed is missing in the representation above. Otherwise it looks great.

**Comment by ayishacs** [comment]
@visheshdembla..
As per our discussion, the metadata-based image filter was to be shown using colored boxes which can be seen on the second screen. Please have a look, but if the team had something new of relevance in mind. Feel free to comment and I will work on it after having a team discussion.

**Comment by visheshdembla** [comment]
Okay got it. I thought we were supposed to show that as a separate section. Let's run this by the instructors once. But before that can we add some text that indicates organization functionality because having that inside the screen doesn't make things clear for me at least. A text would help. Any other feedback @surajp28

**Comment by surajp28** [comment]
I had the following points:
1. The photo-sharing could be shown via panorama. The current diagram doesn't capture the essence of sharing via panorama. A suggestion for the same would be to club upload and download under sharing so we should upload and download as functionality and the text would be entered as - Allows sharing of photos with other users.
2. The cloud storage text could be more elaborate - 'Stores your photos on the cloud' or 'Save your photos at a remote storage'
3. The organization point has been implemented but it isn't easily visible. We could either enter a text there to make it more apparent - 'Organizes your photos for ease of accessibility'.
4. Instead of naming the entire diagram as Panorama, could we mention it on the computer to show where our application fits?
Kindly let me know if a point requires more elaboration.
P.S - @ayishacs - The diagram looks really simple and elegant(As expected). Captures most of the prominent features.

**Comment by visheshdembla** [comment]
As discussed in the meeting today, @ayishacs would work on points 1 and 3.

**Comment by ayishacs** [comment]
Thank you for your feedback @surajp28 

Addressing the inputs, here is my view as discussed in the team meeting:

1. Emphasis is on illustration of the application as a whole, which includes upload, download, sharing, viewing and granting access. The diagram covers all of these as agreed during the team meeting.
2. Keeping it simple and clear is the ultimate goal which we as a team are trying to achieve. Please look for the keywords such as upload photos, download photos and pointers to cloud storage, which covers sharing photos.
3. In response to point 3 and 4, I would like to say that not everything could be written in the computer screen given the space constraint.  

Minor changes will be updated in the consecutive diagram.

**Comment by ayishacs** [comment]
![panoramanapkindiagram](https://user-images.githubusercontent.com/77846296/106937999-6bb0dc80-66ec-11eb-8f8f-4ed8019b56c1.jpg)

**Comment by visheshdembla** [comment]
@ayishacs can you create a PR for the same to the dev branch and put the diagram under res/imgs/ folder so that we can assign it to be reviewed by the instructors?

**Comment by ayishacs** [comment]
@visheshdembla @surajp28 pull request is already sent and waiting for it to be approved.
