### ISSUE TITLE
Configure github webhooks for jenkins build

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#138]
Integrating jenkins with github via webhooks

**Comment by visheshdembla** [comment]
This issue seems to be redundant as we have already decided to go ahead with circle CI. So I don't get what is the point of creating integration with Jenkins. Could you please focus on building up on what has already been done rather than re-working something that is already in a running condition?

In case you feel circle CI is not going to be enough to cover all the scenarios that we have to implement, could you please give a reasoning as to what are these scenarios that cannot be covered using circle CI and the existing functionality and then proceed with integrating Jenkins to GitHub via WebHooks.


Also, I don't think this was discussed in our team meetings so I believe this issue should not be worked on as it is in the current state.

**Comment by ayishacs** [comment]
Since we haven't got our jetstream VMs yet and we have been instructed to try CI-CD on our local machines. This was an effort to setup CI-CD which is part of mid-term presentations. This was setup to give  a demo on CD part.

**Comment by visheshdembla** [comment]
Could you please answer the question above? Even if for the demo, ideally we should be re-using tools that we are already using in the project and not just piling up tools as it is going to become a mess later on. Please provide answers to the above questions or remove the code pushed as part of this issue once the demo is closed.
Thanks.
