### ISSUE TITLE
Reassigning container ports to avoid port conflict during deployment

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#153]
Noticed that the existing docker files for multiple applications are repeating port numbers which would eventually lead to port conflict at the time of deploying the containers on kubernetes pods

**Application - Container port in current docker files**
panorama-ui  -> 80
auth-service   -> 50051
gateway-service -> 3000
image-service  -> 50054
session-log-service -> Not defined
session-service  -> 50051
user-service -> 50054

**Comment by ayishacs** [comment]
Below ports will be assigned to respective applications,
Requesting team to use this as reference:

**Application - New container ports**
panorama-ui -> 80
auth-service -> 50050
gateway-service -> 50055
image-service -> 50060
session-log-service -> 50065
session-service -> 50070
user-service -> 50075

**Comment by visheshdembla** [comment]
from what I understand since everything is going to work in different pods, we can expose the same port from a container and since different pods would have different networking, it would be taken care of.

Also from your comment above, I can see that there is no port number assigned to session-log-service in the configuration. I can see in the code that the port for that is 50055.

Please stick to the ports in your first comment as it would mean changes to a lot of changes in the codebase. 
if you feel like the port numbers mentioned in the second comment are more appropriate, please make the changes in the code. I would not be taking up this issue as it does not seem a priority to me to change the port numbers in the codebase. 

I will expose the correct ports in the docker file and push those changes, 
but these would be the ports I would be exposing as they are like that in our existing codebase

1. gateway-service: 3000
2. auth-service: 50051
3. session-service: 50052
4. user-service: 50053
5. image-service: 50054
6. session-log-service: 50055

**Comment by visheshdembla** [comment]
if you are taking this issue, please ensure the necessary changes are also reflected in the code @ayishacs

**Comment by ayishacs** [comment]
The code base and docker files were updated  as part of this change and as mentioned we will stick with this. @visheshdembla

**Comment by ayishacs** [comment]
@visheshdembla @surajp28 
As and when new application functionalities are added, ensure to update the port numbers in this thread.
So that I can update them in the configuration files.

**Comment by ayishacs** [comment]
Here is the node and port list for all the microservices:
![image](https://user-images.githubusercontent.com/77846296/112779718-546bdc80-9015-11eb-81a3-76d516046ae4.png)
