### ISSUE TITLE
Create a development branch and apply restriction rules

### ISSUE THREAD

**Issue by surajp28** [airavata-courses/Panorama#7]
A development branch would be required to push all commits made by the team members before actually committing to the master branch

**Comment by visheshdembla** [comment]
There was one additional check in the branch protection rules for both the main and the dev branch that we had missed that we needed to add.
Since we all three are admins of the repository, we needed to check the `Include Administrators` check in the options to enforce the rules on us. I checked this option for dev branch as well.

Just FYI.
